launch:
  use_sim_time: true
  use_sim_time_for_control: true
  controller_spawn_delay: 5.0
  controller_manager_timeout: 60.0
  mtc_start_delay: 8.0
  spawn_aux_controllers: true
  launch_mtc_rviz: true
