mtc_pick_place_demo:
  ros__parameters:
    arm_group_name: arm
    hand_group_name: hand
    hand_frame: panda_panda_hand
    world_frame: world
    object_name: demo_cube
    support_surface: demo_table

    pregrasp: open
    grasp: close
    task_timeout_sec: 180.0
    execute: true
    keep_alive_after_execute_failure: true
    auto_run_on_start: true

    pick_pose_xyz: [0.55, 0.0, 0.60]
    place_pose_xyz: [0.55, 0.0, 0.60]

    object_size_xyz: [0.04, 0.04, 0.12]
    support_surface_xyz: [0.55, 0.0, 0.49]
    support_surface_size_xyz: [0.8, 0.8, 0.10]
    grasp_x_offset: -0.1
    grasp_y_offset: 0.0
    grasp_z_offset: 0.0
    grasp_rpy: [0.785, 0.0, 0.0]
    grasp_angle_delta: 0.261799388
    grasp_max_ik_solutions: 4
    grasp_ik_ignore_collisions: true
    additional_allowed_collision_links: [panda_panda_link7, panda_panda_link6]
    #---上面的参数不要改动，下面的参数可以根据需要调整---
    goal_joint_tolerance: 0.00001
    approach_min_distance: 0.0
    approach_distance: 0.10
    lift_min_distance: 0.005
    lift_distance: 0.12
    place_lower_min_distance: 0.0
    place_lower_distance: 0.13
    place_retreat_distance: 0.03
    move_to_pick_timeout_sec: 15.0
    move_to_place_timeout_sec: 5.0
    plan_velocity_scaling: 0.1
    plan_acceleration_scaling: 0.1
    cartesian_step_size: 0.005
    place_max_ik_solutions: 4
