mtc_pick_place_demo:
  ros__parameters:
    arm_group_name: arm
    hand_group_name: hand
    hand_frame: panda_panda_hand
    world_frame: world
    object_name: demo_cube
    support_surface: ""

    pregrasp: open
    grasp: close
    task_timeout_sec: 180.0
    enable_initial_open_hand_stage: false
    enable_move_to_pick_stage: true
    enable_move_to_place_stage: true
    enable_retreat_after_place_stage: true
    enable_forbid_hand_object_collision_after_place: false
    enable_move_home_stage: false

    pick_pose_xyz: [0.55, 0.0, 0.60]
    place_pose_xyz: [0.55, 0.0, 0.60]

    object_size_xyz: [0.04, 0.04, 0.12]
    grasp_x_offset: -0.1
    grasp_y_offset: 0.0
    grasp_z_offset: 0.0
    grasp_rpy: [0.785, 0.0, 0.0]
    grasp_angle_delta: 0.261799388
    grasp_max_ik_solutions: 4
    grasp_ik_ignore_collisions: true
    additional_allowed_collision_links: [panda_panda_link7, panda_panda_link6]
    enable_allow_grasp_collision_stage: true

    approach_min_distance: 0.0
    approach_distance: 0.12
    lift_distance: 0.12
    place_retreat_distance: 0.03
